base_frame_id: robot_footprint
beam_skip_distance: 0.5
beam_skip_threshold: 0.3
do_beamskip: false
first_map_only: false
global_frame_id: map
gui_publish_rate: -1.0
id: 0
kld_err: 0.01
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_max_beams: 30
laser_max_range: 15.0
laser_min_range: -1.0
laser_model_type: likelihood_field_prob
laser_sigma_hit: 0.2
laser_z_hit: 0.9
laser_z_max: 0.05
laser_z_rand: 0.1
laser_z_short: 0.1
max_particles: 1500
min_particles: 500
name: Default
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.2
odom_frame_id: odom
odom_model_type: diff-corrected
parent: 0
recovery_alpha_fast: 0.0
recovery_alpha_slow: 0.0
resample_interval: 1
restore_defaults: false
save_pose_rate: 0.5
state: true
tf_broadcast: true
transform_tolerance: 0.1
type: ''
update_min_a: 0.1
update_min_d: 0.1
use_map_topic: false
gui_publish_rate: -1.0
kld_err: 0.01
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_max_beams: 30
laser_max_range: 15.0
laser_min_range: -1.0
laser_model_type: likelihood_field_prob
laser_sigma_hit: 0.2
laser_z_hit: 0.9
laser_z_max: 0.05
laser_z_rand: 0.1
laser_z_short: 0.1
max_particles: 1500
min_particles: 500
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.2
odom_frame_id: odom
odom_model_type: diff-corrected
recovery_alpha_fast: 0.0
recovery_alpha_slow: 0.0
resample_interval: 1
restore_defaults: false
save_pose_rate: 0.5
tf_broadcast: true
transform_tolerance: 0.1
update_min_a: 0.1
update_min_d: 0.1
use_map_topic: false
